# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!

target 'QuarkWebViewController' do

pod 'VasSonic', '2.0.0-beta'
pod "AFNetworking", "3.1.0"
pod "ReactiveCocoa", "2.5"
pod 'Masonry'
pod 'NJKWebViewProgress'


end

